vtc_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: vtc_dwh
      port: 5432
      dbname: vtc_db
      schema: staging
      threads: 4
      keepalives_idle: 0
